on:
  push:
    branches:
    - sit
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: eservice-sit/isobar-eservice-theme ## ex. src
          dest_dir: eservice-sit/isobar-eservice-theme ## ex. my-theme
          portal_id: ${{ secrets.uat_account_id }}