on:
  push:
    branches:
    - uat
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: /home/rafal/study/hubspot/eservice-hubspot-lp ## ex. src
          dest_dir: isobar-eservice-theme ## ex. my-theme
          portal_id: ${{ secrets.uat_account_id }}
          personal_access_key: ${{ secrets.uat_hubspot_personal_access_key }}